# docker-compose.yml
  version: '3.7'
  services:
    web:
      build: .
      depends_on:
        - db
      ports:
        - "8000:8000"
      volumes:
        - .:/opt/app
        - /opt/app/node_modules
  
    db:
      image: mongo
      expose:
        - "27017"
      volumes:
        - mongodata:/data/db

  volumes:
    mongodata:

